apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::891366442324:role/eksctl-eksctl-demo-nodegroup-ng-f-NodeInstanceRole-1L43RZPECT912
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::891366442324:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-30T19:13:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1453"
  uid: e01a3e60-7ec4-4b4b-8c0c-4c0c496debdf
